import {StyleSheet} from 'react-native';
import {color, colorTutor_} from '../../config/color';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: colorTutor_.ipalBlue,
  },
  imageView: {
    marginTop: hp('3'),
    marginBottom: hp('1'),
    height: hp('20'),
    width: wp('36'),
  },
  topText: {
    color: colorTutor_.TxtColor,
    fontSize: hp('3.0'),
  },
  midView: {
    borderRadius: 5,
    backgroundColor: 'white',
    width: wp('85'),
    alignSelf: 'center',
    alignItems: 'center',
    marginRight: wp('8'),
    marginLeft: wp('7.1'),
  },
  midViewTopView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: hp('4'),
    paddingLeft: wp('2'),
    paddingRight: wp('2'),
  },
  desc: {
    color: colorTutor_.TxtColor,
    fontSize: hp('1.8'),
    width: wp('65'),
    marginTop: hp('3'),
    textAlign: 'center',
    fontStyle: 'italic',
    letterSpacing: 1,
  },
  midLastView: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: hp('4'),
    marginBottom: hp('2'),
  },
  arrowView: {
    borderRadius: 20,
    backgroundColor: colorTutor_.lightAquaGreen,
    padding: 4,
    alignItems: 'center',
    width: wp('20'),
  },
  skipBtn: {
    borderRadius: 30,
    backgroundColor: colorTutor_.ipallightGreen,
    alignItems: 'center',
    width: wp('35'),
    marginHorizontal: wp('3'),
    justifyContent: 'center',
  },
  homeBtn: {
    padding: 8,
    borderRadius: 30,
    alignItems: 'center',
    width: wp('41'),
    justifyContent: 'center',
  },
  bottomView: {
    position: 'absolute',
    bottom: hp('13.5'),
    alignSelf: 'center',
    width: wp('84'),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bottomBar: {
    position: 'absolute',
    backgroundColor: colorTutor_.blue,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    height: hp('9'),
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    bottom: 0,
    width: wp('100'),
    paddingHorizontal: wp('10'),
  },
});
